version: '3.8'

services:
  api:
    build:
      context: ./api
    volumes:
      - sqlite-data:/app/data
    ports:
      - "8081:5000"

  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  sqlite-data: